src/blog/urls.py
from django.contrib.auth.decorators import login_required
from django.urls import path
from .views import BlogHome, BlogPostCreate, BlogPostEdit, BlogPostDetail, BlogPostDelete

app_name = "blog"

urlpatterns = [
    path('', BlogHome.as_view(), name="home"),
    path('create/', login_required(BlogPostCreate.as_view()), name="create"),
    path('<str:slug>/', BlogPostDetail.as_view(), name="post"),
    path('edit/<str:slug>/', BlogPostEdit.as_view(), name="edit"),
    path('delete/<str:slug>/', BlogPostDelete.as_view(), name="delete"),
]

src/myblog/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from myblog import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('blog/', include('blog.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/blog/models.py
from django.contrib.auth import get_user_model
from django.template.defaultfilters import slugify
from django.db import models
from django.urls import reverse

User = get_user_model()


class BlogPost(models.Model):
    title = models.CharField(max_length=255, unique=True, verbose_name="Titre")
    slug = models.SlugField(max_length=255, unique=True, blank=True)
    author = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True)
    last_updated = models.DateTimeField(auto_now=True)
    created_on = models.DateField(blank=True, null=True)
    published = models.BooleanField(default=False, verbose_name="Publié")
    content = models.TextField(blank=True, verbose_name="Contenu")
    thumbnail = models.ImageField(blank=True, upload_to='blog')

    class Meta:
        ordering = ['-created_on']
        verbose_name = "Article"

    def __str__(self):
        return self.title

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.title)
        super().save(*args, **kwargs)

    @property
    def author_or_default(self):
        return self.author.username if self.author else "L'auteur est inconnu"

    def get_absolute_url(self):
        return reverse('blog:home')

src/blog/views.py
# from django.shortcuts import render
from django.views.generic import ListView, CreateView, UpdateView, DetailView, DeleteView
from django.urls import reverse_lazy
from blog.models import BlogPost


class BlogHome(ListView):
    model = BlogPost
    context_object_name = "posts"

    def get_queryset(self):
        queryset = super().get_queryset()
        if self.request.user.is_authenticated:
            return queryset
        return queryset.filter(published=True)


class BlogPostCreate(CreateView):
    model = BlogPost
    template_name = "blog/blogpost_create.html"
    fields = ["title", "content"]


class BlogPostEdit(UpdateView):
    model = BlogPost
    template_name = "blog/blogpost_edit.html"
    fields = ["title", "content", "published", ]


class BlogPostDetail(DetailView):
    model = BlogPost
    template_name = "blog/blogpost_detail.html"


class BlogPostDelete(DeleteView):
    model = BlogPost
    success_url = reverse_lazy("blog:home")

src/blog/templates/blog/blogpost_confirm_delete.html
{% extends 'base.html' %}
{% load static %}
{% block title %} <title>Supprimer des articles</title> {% endblock %}

{% block content %}
    <form method="POST">
        {% csrf_token %}
        <p>Etes vous sûr de vouloir supprimer: {{ object }}</p>
        <input type="submit" value="OUI, Supprimez" class="btn btn-delete">
    </form>
{% endblock %}

src/blog/templates/blog/blogpost_create.html
{% extends 'base.html' %}
{% load static %}
{% block title %} <title>Ajouter des articles</title> {% endblock %}

{% block content %}
     <h1>Ajouter un article</h1>
    <form method="POST">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="créer" class="btn btn-submit">
    </form>
{% endblock %}

src/blog/templates/blog/blogpost_detail.html
{% extends 'base.html' %}
{% load static %}
{% block title %} <title>{{ object.title }}</title> {% endblock %}

{% block content %}
    <article class="post-detail">
        <h2> {{ object.title}} </h2>
        <img src=" {{ object.thumbnail.url }} " alt="L'image de l'article">
        <div> {{ object.content|linebreaks|safe }} </div>
    </article>
{% endblock %}

src/blog/templates/blog/blogpost_edit.html
{% extends 'base.html' %}
{% load static %}
{% block title %} <title>Modifier des articles</title> {% endblock %}

{% block content %}
     <h1>Modifier un article</h1>
    <form method="POST">
        {% csrf_token %}
        {{ form }}
        <input type="submit" value="Modifier" class="btn btn-submit">
    </form>
{% endblock %}

src/blog/templates/blog/blogpost_list.html
{% extends 'base.html' %}
{% load static %}
{% block title %} <title>Accueil du blog</title> {% endblock %}

{% block content %}
<h1>Blog de docstring</h1>
    {% for post in posts %}
        <article>
            <div class="post-title">
            <h2> {{post.title}} </h2>
                {% if request.user.is_authenticated %}
                <div>
                    <a href=" {% url 'blog:edit' slug=post.slug %} "> Editer</a>
                    <a href=" {% url 'blog:delete' slug=post.slug %} "> Supprimer</a>
                </div>
                {% endif %}
            </div>

            <h5 class="post-author"> Publié par <i>{{ post.author_or_default }}</i> le {{ post.created_on|date:'J F Y' }} </h5>
            <p class="post-excerpt">{{ post.content|safe|truncatewords:50 }}</p>

            <form action="{% url 'blog:post' slug=post.slug %}">
                <button class="btn btn-submit">Lire l'article</button>
            </form>
        </article>
    {% endfor %}

{% endblock %}

src/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    {% block title %} {% endblock %}
</head>
<body>
    <nav>
        <a href=" {% url 'blog:home' %} "> Accueil</a>
        {% if request.user.is_authenticated %}
            <a href=" {% url 'blog:create' %} "> Ajouter un article</a>
        {% endif %}
    </nav>
    <section id="blog">
        {% block content %}
        {% endblock %}
    </section>
</body>
</html>